# Generated by Django 4.0.2 on 2022-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Issue',
            },
        ),
    ]
