# Generated by Django 4.0.2 on 2022-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaelimRestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isFilter',
            field=models.CharField(max_length=5),
        ),
    ]
