# Generated by Django 4.0.2 on 2022-02-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaelimRestAPI', '0002_alter_question_isfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isFilter',
            field=models.IntegerField(),
        ),
    ]
