# Generated by Django 4.0.2 on 2022-02-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaelimRestAPI', '0003_alter_question_isfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
