# Generated by Django 4.0.2 on 2022-02-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaelimRestAPI', '0004_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicBuilding', models.CharField(max_length=50)),
                ('facilityName', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
            ],
            options={
                'db_table': 'Facility',
            },
        ),
    ]
